sudo: required
services:
  - docker

before_install:
  - docker build -t manuelbautista/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run manuelbautista/react-test npm test -- --coverage

after_success:
  - docker build -t b0hcoder/multi-client ./client
  - docker build -t b0hcoder/multi-nginx ./nginx
  - docker build -t b0hcoder/multi-server ./server
  - docker build -t b0hcoder/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push b0hcoder/multi-client
  - docker push b0hcoder/multi-nginx
  - docker push b0hcoder/multi-server
  - docker push b0hcoder/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-009626857352
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: $AWS_SECRET_KEY