version: '3'
services:
  postgres:  #el nombre del servicio que le puse al container de postgres
    image: 'postgres:latest'  #el container de postgres del hub.docker.com
  redis:
    image: 'redis:latest'
  nginx:
    restart: always  #si algo falla, reinicia el nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'  #puerto 3050 en mi local machine de la 80 del container
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules  #deja ese folder como esta
      - ./server:/app   #cuando hagamos un cambio al /server se reflejara automaticamente al /app del container
    environment:
      - REDIS_HOST=redis #redis service name
      - REDIS_PORT=6379 #default port
      - PGUSER=postgres #default user
      - PGHOST=postgres  #service name
      - PGDATABASE=postgres  #default db
      - PGPASSWORD=postgres_password  #default password
      - PGPORT=5432 #default port
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app